name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "."
  NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    timeout-minutes: 60
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Clear Previous Node Modules Cache (if needed)
        run: |
          gh extension install actions/gh-actions-cache
          cacheKeys=$(gh actions-cache list -B ${{ github.repository_id }} | grep modules | awk '{print $1}')
          for key in $cacheKeys; do
            gh actions-cache delete $key -B ${{ github.repository_id }} --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci --ignore-scripts
        working-directory: ${{ env.BUILD_PATH }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Set and log environment secrets and variables and then Build with Astro and postbuild for pagefind
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          GITHUB_PAGES: true
          SITE: ${{ steps.pages.outputs.origin }}
          BASE: ${{ steps.pages.outputs.base_path }}
        run: |
          echo "NOTION_API_SECRET = $NOTION_API_SECRET"
          echo "GITHUB_PAGES = $GITHUB_PAGES"
          echo "SITE = $SITE"
          echo "BASE = $BASE"
          npx --no-install astro build
          # or if you prefer yarn, use: yarn build
          # --site and --base flags can be included if needed for Astro
          # --site steps.pages.outputs.origin" \
          # --base steps.pages.outputs.base_path"
          npx --no-install pagefind --site dist
        working-directory: ${{ env.BUILD_PATH }}

      - name: Clear Previous `tmp` and `public` Cache (if needed)
        run: |
          gh extension install actions/gh-actions-cache
          for key in $(gh actions-cache list -B ${{ github.repository_id }} | grep blogtrotion | awk '{print $1}'); do
            gh actions-cache delete $key -B ${{ github.repository_id }} --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save New `tmp` Cache
        id: cache-tmp-save
        uses: actions/cache/save@v4
        with:
          path: ./tmp
          key: tmp-webtrotion-${{ github.repository_id }}

      - name: Save New `public` Cache
        id: cache-public-save
        uses: actions/cache/save@v4
        with:
          path: ./public
          key: public-webtrotion-${{ github.repository_id }}

            # Idea from https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/

      - name: Save node cache manually
        id: npm-cache-save
        uses: actions/cache/save@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles(format('{0}/package-lock.json', env.BUILD_PATH)) }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
